# Generated by Django 4.0.3 on 2022-04-15 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile_pics\\default.png', upload_to='profile_pics'),
        ),
    ]
