# Generated by Django 4.0.3 on 2022-04-20 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0003_alter_song_person'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='person',
            new_name='author',
        ),
    ]
