# Generated by Django 4.0.3 on 2022-04-09 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0005_auto_20200712_1306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='language',
        ),
        migrations.AddField(
            model_name='song',
            name='genre',
            field=models.CharField(choices=[('Hiphop', 'Hiphop'), ('Classic', 'Classic')], default='Hiphop', max_length=20),
        ),
    ]
