# Generated by Django 4.0.3 on 2022-04-14 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0007_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
