# Generated by Django 4.0.3 on 2022-04-20 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0007_song_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='person',
        ),
    ]
