# Generated by Django 4.0.3 on 2022-04-20 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0009_song_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='author',
        ),
    ]
