# Generated by Django 4.0.3 on 2022-04-17 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0011_alter_song_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='genre',
            field=models.CharField(choices=[('Hiphop', 'Hiphop'), ('Classic', 'Classic'), ('Pop', 'Pop')], default='Hiphop', max_length=20),
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
    ]
